% date(2026,3,5)

lib_index(arg, 4, any, stoics_lib, 'term/arg').
lib_index(arg, 5, any, stoics_lib, 'term/arg').
lib_index(arg_add, 4, any, stoics_lib, 'term/arg_add').
lib_index(arity, 2, any, stoics_lib, 'term/arity').
lib_index(arity, 3, any, stoics_lib, 'term/arity').
lib_index(at_con, 2, any, stoics_lib, 'atom/at_con').
lib_index(at_con, 3, any, stoics_lib, 'atom/at_con').
lib_index(atom_replace, 4, any, stoics_lib, 'atom/atom_replace').
lib_index(atom_sub, 2, any, stoics_lib, 'atom/atom_sub').
lib_index(break_nth, 4, any, stoics_lib, 'list/break_nth').
lib_index(break_on_list, 4, any, stoics_lib, 'list/break_on_list').
lib_index(call_morph, 4, any, stoics_lib, 'meta/call_morph').
lib_index(colour_hex, 2, any, stoics_lib, 'colour/colour_hex').
lib_index(compare, 4, any, stoics_lib, 'term/compare').
lib_index(compare_arithmetic, 3, any, stoics_lib, 'number/compare_arithmetic').
lib_index(compound, 3, any, stoics_lib, 'term/compound').
lib_index(current_call, 1, any, stoics_lib, 'meta/current_call').
lib_index(current_call, 2, any, stoics_lib, 'meta/current_call').
lib_index(curtail, 3, any, stoics_lib, 'term/curtail').
lib_index(date_two_digit_dotted, 1, any, stoics_lib, 'date_time/date_two_digit_dotted').
lib_index(date_two_digit_dotted, 2, any, stoics_lib, 'date_time/date_two_digit_dotted').
lib_index(datime_readable, 1, any, stoics_lib, 'date_time/datime_readable').
lib_index(datime_readable, 2, any, stoics_lib, 'date_time/datime_readable').
lib_index(en_append, 3, any, stoics_lib, 'list/en_append').
lib_index(en_list, 2, any, stoics_lib, 'term/en_list').
lib_index(en_list, 3, any, stoics_lib, 'term/en_list').
lib_index(even, 1, any, stoics_lib, 'number/even').
lib_index(expand_spec, 2, any, stoics_lib, 'file/expand_spec').
lib_index(functor_term, 2, any, stoics_lib, 'term/functor_term').
lib_index(get_date, 1, any, stoics_lib, 'date_time/get_date').
lib_index(get_date_time, 1, any, stoics_lib, 'date_time/get_date_time').
lib_index(get_datetime, 1, any, stoics_lib, 'date_time/get_datetime').
lib_index(goal, 4, any, stoics_lib, 'meta/goal').
lib_index(goal_spec, 2, any, stoics_lib, 'meta/goal_spec').
lib_index(has_at_least, 3, any, stoics_lib, 'list/has_at_least').
lib_index(has_at_most, 3, any, stoics_lib, 'list/has_at_most').
lib_index(has_cased, 3, any, stoics_lib, 'codes/has_cased').
lib_index(has_length, 2, any, stoics_lib, 'term/has_length').
lib_index(has_length, 3, any, stoics_lib, 'term/has_length').
lib_index(has_length, 4, any, stoics_lib, 'term/has_length').
lib_index(holds, 2, any, stoics_lib, 'meta/holds').
lib_index(imported_from, 2, any, stoics_lib, 'meta/imported_from').
lib_index(int_trailer, 2, any, stoics_lib, 'number/int_trailer').
lib_index(io_close, 2, any, stoics_lib, 'io/io_close').
lib_index(io_get_line, 2, any, stoics_lib, 'io/io_get_line').
lib_index(io_line, 2, any, stoics_lib, 'io/io_line').
lib_index(io_lines, 2, any, stoics_lib, 'io/io_lines').
lib_index(io_open, 3, any, stoics_lib, 'io/io_open').
lib_index(io_put_line, 2, any, stoics_lib, 'io/io_put_line').
lib_index(io_section, 3, any, stoics_lib, 'io/io_section').
lib_index(io_section_close, 1, any, stoics_lib, 'io/io_section').
lib_index(io_section_open, 3, any, stoics_lib, 'io/io_section').
lib_index(io_sections, 3, any, stoics_lib, 'io/io_sections').
lib_index(io_streams, 3, any, stoics_lib, 'io/io_streams').
lib_index(io_url, 1, any, stoics_lib, 'io/io_url').
lib_index(known, 1, any, stoics_lib, 'meta/known').
lib_index(known, 2, any, stoics_lib, 'meta/known').
lib_index(kv_compose, 3, any, stoics_lib, 'kv/kv_compose').
lib_index(kv_compose, 4, any, stoics_lib, 'kv/kv_compose').
lib_index(kv_compose_k_frequency, 2, any, stoics_lib, 'kv/kv_compose_k_frequency').
lib_index(kv_compose_k_frequency, 3, any, stoics_lib, 'kv/kv_compose_k_frequency').
lib_index(kv_compose_k_nth, 3, any, stoics_lib, 'kv/kv_compose_k_nth').
lib_index(kv_decompose, 3, any, stoics_lib, 'kv/kv_decompose').
lib_index(kv_k_vs, 2, any, stoics_lib, 'kv/kv_k_vs').
lib_index(kv_k_vs, 3, any, stoics_lib, 'kv/kv_k_vs').
lib_index(kv_ks, 2, any, stoics_lib, 'kv/kv_ks').
lib_index(kv_transpose, 2, any, stoics_lib, 'kv/kv_transpose').
lib_index(kv_vs, 2, any, stoics_lib, 'kv/kv_vs').
lib_index(kvo_k_until_vs,3, any, stoics_lib, 'kv/kvo_k_until_vs' ).
lib_index(kvo_k_until_vs,4, any, stoics_lib, 'kv/kvo_k_until_vs' ).
lib_index(kvo_k_memberchk, 3, any, stoics_lib, 'kv/kvo_k_memberchk').
lib_index(kvs_k_memberchk, 3, any, stoics_lib, 'kv/kvs_k_memberchk').
lib_index(latex_colour, 4, any, stoics_lib, 'colour/latex_colour').
lib_index(letter_strings, 3, any, stoics_lib, 'string/letter_strings').
lib_index(lexi, 2, any, stoics_lib, 'codes/lexi').
lib_index(lexi_n, 4, any, stoics_lib, 'codes/lexi_n').
lib_index(list_frequency, 2, any, stoics_lib, 'list/list_frequency').
lib_index(list_frequency, 3, any, stoics_lib, 'list/list_frequency').
lib_index(list_is_invariant, 1, any, stoics_lib, 'list/list_is_invariant').
lib_index(list_proportions, 2, any, stoics_lib, 'list/list_proportions').
lib_index(list_proportions, 3, any, stoics_lib, 'list/list_proportions').
lib_index(list_transpose, 2, any, stoics_lib, 'list/list_transpose').
lib_index(locate, 3, any, stoics_lib, 'file/locate').
lib_index(map_list_options, 3, any, stoics_lib, 'meta/map_list_options').
lib_index(map_list_options, 4, any, stoics_lib, 'meta/map_list_options').
lib_index(map_succ_list, 3, any, stoics_lib, 'meta/map_succ_list').
lib_index(map_succ_list, 4, any, stoics_lib, 'meta/map_succ_list').
lib_index(maparg, 2, any, stoics_lib, 'meta/maparg').
lib_index(maparg, 3, any, stoics_lib, 'meta/maparg').
lib_index(maparg, 4, any, stoics_lib, 'meta/maparg').
lib_index(message_report, 3, any, stoics_lib, 'error/message_report').
lib_index(min_max, 3, any, stoics_lib, 'list/min_max').
lib_index(mod_goal, 2, any, stoics_lib, 'meta/mod_goal').
lib_index(mod_goal, 3, any, stoics_lib, 'meta/mod_goal').
lib_index(mod_goal, 4, any, stoics_lib, 'meta/mod_goal').
lib_index(n_breaks, 4, any, stoics_lib, 'list/n_breaks').
lib_index(n_digits_integer_codes, 3, any, stoics_lib, 'codes/n_digits_integer_codes').
lib_index(n_digits_min, 3, any, stoics_lib, 'number/n_digits_min').
lib_index(nth1, 5, any, stoics_lib, 'list/nth1').
lib_index(odd, 1, any, stoics_lib, 'number/odd').
lib_index(on_call, 4, any, stoics_lib, 'meta/on_call').
lib_index(on_fail, 2, any, stoics_lib, 'meta/on_fail').
lib_index(on_fail, 3, any, stoics_lib, 'meta/on_fail').
lib_index(op_compare, 3, any, stoics_lib, 'term/op_compare').
lib_index(portray_clauses, 2, any, stoics_lib, 'term/portray_clauses').
lib_index(position, 3, any, stoics_lib, 'term/position').
lib_index(position, 4, any, stoics_lib, 'term/position').
lib_index(position, 6, any, stoics_lib, 'term/position').
lib_index(position_nth, 3, any, stoics_lib, 'term/position_nth').
lib_index(position_nth, 4, any, stoics_lib, 'term/position_nth').
lib_index(position_nth, 5, any, stoics_lib, 'term/position_nth').
lib_index(position_nth, 6, any, stoics_lib, 'term/position_nth').
lib_index(position_type, 2, any, stoics_lib, 'term/position_type').
lib_index(positions, 2, any, stoics_lib, 'term/positions').
lib_index(positions, 3, any, stoics_lib, 'term/positions').
lib_index(prefix_atom, 2, any, stoics_lib, 'atom/prefix_atom').
lib_index(prefix_atom, 3, any, stoics_lib, 'atom/prefix_atom').
lib_index(select_all, 4, any, stoics_lib, 'list/select_all').
lib_index(select_first, 3, any, stoics_lib, 'list/select_first').
lib_index(skim, 3, any, stoics_lib, 'list/skim').
lib_index(stoics_lib, 0, any, stoics_lib, 'auxil/stoics_lib_module').
lib_index(stoics_lib_version, 2, any, stoics_lib, 'auxil/stoics_lib_module').
lib_index(sub_atom, 2, any, stoics_lib, 'atom/sub_atom').
lib_index(sub_atom, 4, any, stoics_lib, 'atom/sub_atom').
lib_index(term_length, 2, any, stoics_lib, 'term/term_length').
lib_index(term_type, 2, any, stoics_lib, 'term/term_type').
lib_index(termplate, 2, any, stoics_lib, 'term/termplate').
lib_index(termplate, 3, any, stoics_lib, 'term/termplate').
lib_index(three_letter_month, 2, any, stoics_lib, 'date_time/three_letter_month').
lib_index(three_letter_months, 1, any, stoics_lib, 'date_time/three_letter_months').
lib_index(url_file, 2, any, stoics_lib, 'web/url_file').
lib_index(url_file, 3, any, stoics_lib, 'web/url_file').
lib_index(which, 3, any, stoics_lib, 'meta/which').
% manual: 
lib_index(day_trailer, 2, any, stoics_lib, 'date_time/day_trailer').
lib_index(get_date_time, 1, any, stoics_lib, 'date_time/get_date_time').
lib_index(int_trailer, 2, any, stoics_lib, 'number/int_trailer').
lib_index(stoics_lib_throw, 2, any, stoics_lib, 'auxil/stoics_lib_throw').
lib_index(three_letter_months, 1, any, stoics_lib, 'date_time/three_letter_months').
