#!/bin/sh -f
### BEGIN INIT INFO
# this is a direct copy&change of the script provided by SWI 
# Provides:          swi-spuds
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/stop SWI-Prolog spuds server
### END INIT INFO

# Installation
#
#   1. Copy this file to /etc/init.d/swi-spuds
#   2. Edit the Configuration section below
#   3. Run the following 2 commands (as sudo)
#	 % update-rc.d swipl-spuds defaults
#	 % /etc/init.d/swipl-spuds start

# Configuration section
#
SWIPL=/usr/local/users/nicos/local/git/bin/swipl
DIR=/srv/www/html/spuds/server
SCRIPT=spuds_daemon
USER=nicos
HOME=/home/$USER
# on my setup when server starts at boot, these are not set-up properly:
ENV="USER=$USER HOME=$HOME"  
PORT=4004
DAEMONARGS=

# Uncomment to only listen for connections from localhost
# DAEMONARGS="$DAEMONARGS --ip=localhost"

SPUDSID=swipl-spuds-$PORT
PIDFILE=/var/run/$SPUDSID.pid
SYSLOG=/var/run/$SPUDSID

# End of normal configuration

. /lib/lsb/init-functions
test -f /etc/default/rcS && . /etc/default/rcS

DAEMONARGS="$DAEMONARGS --port=$PORT --user=$USER --fork"
if [ ! -z "$SYSLOG" ]; then DAEMONARGS="$DAEMONARGS --syslog=$SYSLOG"; fi
if [ ! -z "$PIDFILE" ]; then DAEMONARGS="$DAEMONARGS --pidfile=$PIDFILE"; fi

pidofserver()
{ if [ -f "$PIDFILE" ]; then
    cat "$PIDFILE"
  else
    ps aux | grep "[0-9] *$SWIPL.*--port=$PORT" 2>/dev/null | awk '{print $2}'
  fi
}

running()
{ if [ -z "$1" ]; then return 1; fi

  if kill -0 $1 2> /dev/null; then
    return 0
  else
    return 1
  fi
}

waitserver()
{ i=0;

  while running $1; do
    if [ $i = '60' ]; then
      return 1;
    else
      if [ $i = '0' ]; then
        echo -n " ... waiting "
      else
        echo -n "."
      fi
      i=$(($i+1))
      sleep 1
    fi
  done
}

case $1 in
        start)
	  log_daemon_msg "Starting spuds server" "$SPUDSID"
	  if (cd $DIR && env $ENV $SWIPL -f none -q -s $SCRIPT -- $DAEMONARGS); then
	    log_end_msg 0
	  else
	    log_end_msg 1
	  fi
        ;;
        debug)
	  log_daemon_msg "Debugging spuds server" "$SPUDSID"
	  # echo cd $DIR '::' $SWIPL -f none -q -s $SCRIPT -- $DAEMONARGS --spuds_debug=true  # might want to  uncomment this if you are debugging 
	  if (cd $DIR && $SWIPL -f none -q -s $SCRIPT -- $DAEMONARGS --spuds_debug=true); then
	    log_end_msg 0
	  else
	    log_end_msg 1
	  fi
        ;;
	stop)
	  log_daemon_msg "Stopping spuds server" "$SPUDSID"
	  PID=$(pidofserver)
	  kill $PID
	  if waitserver $PID; then
	    log_end_msg 0
	  else
	    kill -9 $PID
	    waitserver $PID
	  fi
	;;
	restart)
	  $0 stop && $0 start
	;;
	status)
	  PID=$(pidofserver)
	  if running "$PID"; then
	    echo "SWI-Prolog spuds server is running (pid $PID)."
	    exit 0
	  else
	    echo "SWI-Prolog spuds server is NOT running."
	    if [ -e $PIDFILE ]; then
	      exit 1
	    else
	      exit 3
	    fi
	  fi
	;;
	*)
	log_success_msg "Usage: /etc/init.d/swipl-spuds {start|stop|restart|status}"
	exit 1
esac
