% date(2026,3,5)

lib_index(os_abs, 2, any, os_lib, os_abs).
lib_index(os_abs, 3, any, os_lib, os_abs).
lib_index(os_base, 2, any, os_lib, os_base).
lib_index(os_cast, 2, any, os_lib, os_cast).
lib_index(os_cast, 3, any, os_lib, os_cast).
lib_index(os_cp, 2, any, os_lib, os_cp).
lib_index(os_dir, 1, any, os_lib, os_dir).
lib_index(os_dir, 2, any, os_lib, os_dir).
lib_index(os_dir_stem_ext, 2, any, os_lib, os_dir_stem_ext).
lib_index(os_dir_stem_ext, 4, any, os_lib, os_dir_stem_ext).
lib_index(os_dirs, 1, any, os_lib, os_dirs).
lib_index(os_dirs, 2, any, os_lib, os_dirs).
lib_index(os_exists, 1, any, os_lib, os_exists).
lib_index(os_exists, 2, any, os_lib, os_exists).
lib_index(os_ext, 2, any, os_lib, os_ext).
lib_index(os_ext, 3, any, os_lib, os_ext).
lib_index(os_ext, 4, any, os_lib, os_ext).
lib_index(os_file, 1, any, os_lib, os_file).
lib_index(os_file, 2, any, os_lib, os_file).
lib_index(os_files, 1, any, os_lib, os_files).
lib_index(os_files, 2, any, os_lib, os_files).
lib_index(os_lib_version, 2, any, os_lib, '../prolog/os_lib').
lib_index(os_ln_s, 2, any, os_lib, os_ln_s).
lib_index(os_make_path, 1, any, os_lib, os_make_path).
lib_index(os_make_path, 2, any, os_lib, os_make_path).
lib_index(os_mill, 4, any, os_lib, os_mill).
lib_index(os_mv, 2, any, os_lib, os_mv).
lib_index(os_name, 2, any, os_lib, os_name).
lib_index(os_parts, 2, any, os_lib, os_parts).
lib_index(os_parts, 3, any, os_lib, os_parts).
lib_index(os_path, 2, any, os_lib, os_path).
lib_index(os_path, 3, any, os_lib, os_path).
lib_index(os_postfix, 2, any, os_lib, os_postfix).
lib_index(os_postfix, 3, any, os_lib, os_postfix).
lib_index(os_postfix, 4, any, os_lib, os_postfix).
lib_index(os_remove, 1, any, os_lib, os_remove).
lib_index(os_remove, 2, any, os_lib, os_remove).
lib_index(os_repoint, 2, any, os_lib, os_repoint).
lib_index(os_rm, 1, any, os_lib, os_rm).
lib_index(os_rm, 2, any, os_lib, os_rm).
lib_index(os_sel, 3, any, os_lib, os_sel).
lib_index(os_sel, 4, any, os_lib, os_sel).
lib_index(os_sep, 1, any, os_lib, os_sep).
lib_index(os_sep, 2, any, os_lib, os_sep).
lib_index(os_slashify, 2, any, os_lib, os_slashify).
lib_index(os_stem, 3, any, os_lib, os_stem).
lib_index(os_term, 2, any, os_lib, os_term).
lib_index(os_tmp_dir, 1, any, os_lib, os_tmp_dir).
lib_index(os_type_base, 2, any, os_lib, os_type_base).
lib_index(os_un_zip, 3, any, os_lib, os_un_zip).
lib_index(os_unique, 2, any, os_lib, os_unique).
lib_index(os_unique, 3, any, os_lib, os_unique).
lib_index(os_version, 2, any, os_lib, '../prolog/os_lib').
